[aws]
symbol = "ğŸ…° "

[battery]
disabled = true

[crystal]
disabled = true

[dart]
disabled = true

[directory]
truncate_to_repo = false
truncation_length = 8
truncation_symbol = "â€¦/"

[dotnet]
disabled = true

[gcloud]
symbol = "ğŸ…¶ "

[git_branch]
symbol = "áš¶ï¸ "

[git_status]
disabled = true

[hg_branch]
symbol = "áš¶ï¸ "
disabled = false

[openstack]
disabled = true

[purescript]
disabled = true

[singularity]
disabled = true

[zig]
disabled = true

[nodejs]
symbol = "ï¢˜   "
format = "via[$symbol($version) ]($style)"
